#!/bin/bash

# FTP login attributes and paths 	
currentFolder=$1												# Zde prosím nastavte plnou cestu, která vede do nynějšího umístění MeteoCam scriptů.
pathToPictures=$2												# Zde prosím nastavte plnou cestu do adresářové struktury Pictures.
userName=$3														# Zde si prosím nastavte uživatelské jméno pro přístup k FTP serveru.
password=$4														# Zde si prosím nastavte heslo pro přístup k uživatelskému účtu na FTP serveru.
domain=$5														# Zde prosím nastavte název vaší domény např. google.com .
destinationFolder=$6											# Zde prosím určete, do jakého adresáře se na zvoleném FTP serveru budou ukládat nově pořízené animace. 
targetDirectory=$7												# Zde prosím nastavte ID cílové složky na Google drive. 
directory=($pathToPictures/Pictures-anim/Pictures-anim12h/)		# Adresář, ve kterém jsou ukládány snímky pro tvorbu dvanáctihodinové animace.

# Nekončící cyklus 
for (( ; ; ))
do
	copy=16																		# Počáteční hodnota přemisťovacího cyklu
	firstAddValue=480															# Hodnota, které je přičítána po prvním průchodu přemisťovacího cyklu.
	frequency=600																# Počet sekund, po kterých bude zahájen proces o tvorbu animace.  
	
	echo "Current animation level directory is: $directory" 

	if [ $(ls -A "$directory" | wc -l) -ge 60 ]; then							# Podmínka, která se ptá, zdali adresář obsahuje dostatečný počet snímků pro tvorbu animace.
		
		DT=$(date '+%Y%m%d%H%M%S')												# Tato proměnná vyjadřuje nynější datum a čas.
		convert -morph 1 -delay 8 $pathToPictures/Pictures-anim/Pictures-anim12h/{16,24,32,40,48,56,64,72,80,88,96,104,112,120,128,136,144,152,160,168,176,184,192,200,208,216,224,232,240,248,256,264,272,280,288,296,304,312,320,328,336,344,352,360,368,376,384,392,400,408,416,424,432,440,448,456,464,472,480,488,496}.jpg $pathToPictures/Pictures-anim/Pictures-anim-final/Pictures-anim12h/$DT.gif	# Tímto příkazem se již generuje samotná animace. Parametrem -morph zvolíme morfologickou image porccessing metodu, která zajistí méně nedokonalostí oproti ostatním metodám. Parametr -delay určuje, po jaké době má být zobrazen další snímek(ms). Dále je zde definováno rozhraní snímků, které budou jako vstup pro tvorbu. Poslední atribut vyjadřuje již cestu k výstupnímu souboru.
		echo "New animation: $DT.gif is ready!"
		cd $pathToPictures/Pictures-anim/Pictures-anim-final/Pictures-anim12h
		$currentFolder/cam-anim-up-12hours "$DT" $pathToPictures $targetDirectory $userName $password $domain $destinationFolder & 					# Spuštění subprocesu pro nahrání animace na webhosting a do Gdrive archivu.
		
		# Zde můžete v případě potřeby přesouvat již hotové animace do archivu, pro povolení této funkce prosím odstraňte křížky v následujících 2 řádcích.  
		# mv $pathToPictures/Pictures-anim/Pictures-anim-final/Pictures-anim12h/"$DT.gif" $pathToPictures/Pictures-anim/Pictures-anim-old/Pictures-anim12h/
		# echo "File $DT.gif has been moved to the archieve!"
	
	# Následující cyklus přesouvá snímky z adresáře s již vytvořenou animací. Z dvanáctihodinové do denní struktury je přesouván každý šestnáctý snímek postupně ve 2 jednotlivých vlnách.		
	while [ $copy -lt 497 ];
	 do
		if [ -e $pathToPictures/Pictures-anim/Pictures-anim1d/"$copy.jpg" ]; then	# Zde se ptáme, zdali již byla někdy provedena první vlna přesunu. Pokud ano, přičítá se k číselné hodnotě snímku další číselná hodnota. Takto předcházíme duplikaci názvů snímků v adresáři.
			let firstDuplicate=$(($copy + $firstAddValue))
			mv $pathToPictures/Pictures-anim/Pictures-anim12h/"$copy.jpg" $pathToPictures/Pictures-anim/Pictures-anim1d/"$firstDuplicate.jpg"
			echo "New picture: $copy.jpg has been moved to the next level animation directory as: $firstDuplicate.jpg!"
		else
			mv $pathToPictures/Pictures-anim/Pictures-anim12h/"$copy.jpg" $pathToPictures/Pictures-anim/Pictures-anim1d/
			echo "New picture: $copy.jpg has been moved to the next level animation directory as: $copy.jpg!"
		fi
		
		let copy=copy+16													# Z dvanáctihodinové do denní struktury je přesouván každý šestnáctý snímek.
		
	done
		rm -r $pathToPictures/Pictures-anim/Pictures-anim12h/*.'jpg' 		# Po přesunu všech potřebných snímků do dalšího adresáře jsou veškeré ostatní snímky z dvanáctihodinového adresáře odstraněny.
		echo "Unnecessary pictures has been removed!" 
	else
		echo "There are not enough files! Only $(ls -A "$directory" | wc -l) files available!"
	fi
		
	echo "Waiting $frequency seconds for the next try..."
	sleep $frequency

done