#!/bin/bash
id="$1"							# Prvním argumentem je vyjádřena vystupní ID v databázi na serveru. 
DT=$(date '+%Y%m%d%H%M%S')		# Tato proměnná vyjadřuje nynější datum a čas. 
echo $DT 
url="$2"						# URL pro snímek je vyjádřena druhým argumentem.
# server login
login="user@server.com"			# Zde vyplňte prosím přihlašovací jeméno a doménu ve fromátu username@doména.cz .  
protocol=22						# Zde vyplňte ID síťového protokolu. U SSH je výchozí ID 22.

# Následující funkce zajišťuje přístup na server pomocí protokolu SSH. Za parametrem -p v uvozovkách prosím vyplňte své heslo pro přístup na SSH. Po úspěšném přístupu vyvolá příkazy nacházející se v EOF. 

ssh host <<EOF
mysql --host=host --user=user --password=password database -e "insert into images (id, url) values('$id','$url')"
EOF

# V příkazu mysql si vyplňte přihlašovací údaje do databáze a nakonfigurujte si pole, do kterých se budou data ukládat.
echo "URL has been successfully saved into the database!" 